name: Build and Push to ECR

on:
  push:
    branches:
      - main  # Set this to the branch you want to deploy from

jobs:
  build-and-push:
    name: Build and Push Docker image to AWS ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        run: |
          echo "Building image for ${{ steps.login-ecr.outputs.registry }}/keeker:latest"
          docker build -t ${{ steps.login-ecr.outputs.registry }}/keeker:latest .
          docker push ${{ steps.login-ecr.outputs.registry }}/keeker:latest

