name: Build and Push to ECR

on:
  push:
    branches:
      - main  # Set this to the branch you want to deploy from

jobs:
  build-and-push:
    name: Build and Push Docker image to AWS ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Ensure this matches your ECR region

      - name: Login to Amazon ECR Public
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/q4k9i1z4

      - name: Build Docker image
        run: |
          docker build -t keeker .

      - name: Tag Docker image
        run: |
          docker tag keeker:latest public.ecr.aws/q4k9i1z4/keeker:latest

      - name: Push Docker image to ECR
        run: |
          docker push public.ecr.aws/q4k9i1z4/keeker:latest

      - name: Output the image name
        run: echo "Docker Image Name: public.ecr.aws/q4k9i1z4/keeker:latest"
